spring:
  datasource:
    url: jdbc:h2:mem:project-template
    username: root
    password:
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: openapi.yaml
logging:
  level:
    .org.springframework.web: DEBUG